import type { WorkspaceData } from './types';

/**
 * Returns a fresh seed workspace. Called on first run (nothing in
 * localStorage) and by "Reset demo data". Dates are static so the demo is
 * deterministic; the newest invoices/time entries land in the current period.
 */
export function seedData(): WorkspaceData {
  return {
    settings: {
      currency: 'USD',
      businessName: 'FreelanceHub',
    },
    clients: [
      {
        id: 'c-acme',
        name: 'Dana Whitfield',
        company: 'Acme Analytics',
        email: 'dana@acmeanalytics.io',
        phone: '+1 415 555 0142',
        status: 'active',
        notes: 'Primary retainer client. Prefers async updates on Fridays.',
        createdAt: '2026-03-02T09:00:00.000Z',
      },
      {
        id: 'c-northwind',
        name: 'Miguel Santos',
        company: 'Northwind Studio',
        email: 'miguel@northwind.studio',
        phone: '+1 512 555 0198',
        status: 'active',
        notes: 'Brand refresh + marketing site.',
        createdAt: '2026-04-18T09:00:00.000Z',
      },
      {
        id: 'c-lumen',
        name: 'Priya Nair',
        company: 'Lumen Health',
        email: 'priya@lumenhealth.com',
        status: 'lead',
        notes: 'Interested in a patient portal MVP. Proposal sent.',
        createdAt: '2026-07-21T09:00:00.000Z',
      },
      {
        id: 'c-oldco',
        name: 'Sam Rivera',
        company: 'Oldco Retail',
        email: 'sam@oldco.example',
        status: 'archived',
        notes: 'Engagement wrapped Q1. Keep for reference.',
        createdAt: '2025-11-05T09:00:00.000Z',
      },
    ],
    projects: [
      {
        id: 'p-dashboard',
        name: 'Analytics Dashboard v2',
        clientId: 'c-acme',
        status: 'active',
        hourlyRate: 120,
        startDate: '2026-06-01',
        dueDate: '2026-09-15',
        description:
          'Rebuild the reporting dashboard with real-time charts and saved views.',
        createdAt: '2026-05-20T09:00:00.000Z',
      },
      {
        id: 'p-retainer',
        name: 'Data Pipeline Retainer',
        clientId: 'c-acme',
        status: 'active',
        hourlyRate: 135,
        startDate: '2026-01-05',
        description: 'Ongoing ETL maintenance and on-call support.',
        createdAt: '2026-01-02T09:00:00.000Z',
      },
      {
        id: 'p-website',
        name: 'Marketing Site Redesign',
        clientId: 'c-northwind',
        status: 'active',
        budget: 14000,
        hourlyRate: 110,
        startDate: '2026-05-10',
        dueDate: '2026-08-30',
        description: 'New marketing site with CMS and blog.',
        createdAt: '2026-05-01T09:00:00.000Z',
      },
      {
        id: 'p-brand',
        name: 'Brand Identity',
        clientId: 'c-northwind',
        status: 'completed',
        budget: 6000,
        startDate: '2026-04-20',
        dueDate: '2026-06-01',
        description: 'Logo, palette, and brand guidelines.',
        createdAt: '2026-04-15T09:00:00.000Z',
      },
      {
        id: 'p-portal',
        name: 'Patient Portal MVP',
        clientId: 'c-lumen',
        status: 'planning',
        hourlyRate: 140,
        startDate: '2026-09-01',
        description: 'Scoping a HIPAA-conscious patient portal MVP.',
        createdAt: '2026-07-22T09:00:00.000Z',
      },
    ],
    invoices: [
      {
        id: 'i-1001',
        number: 'INV-0001',
        clientId: 'c-northwind',
        projectId: 'p-brand',
        status: 'paid',
        issueDate: '2026-06-02',
        dueDate: '2026-06-16',
        lineItems: [
          {
            id: 'li-1',
            description: 'Brand identity — fixed fee',
            quantity: 1,
            unitPrice: 6000,
          },
        ],
        notes: 'Thanks for the great collaboration!',
        createdAt: '2026-06-02T09:00:00.000Z',
      },
      {
        id: 'i-1002',
        number: 'INV-0002',
        clientId: 'c-acme',
        projectId: 'p-retainer',
        status: 'paid',
        issueDate: '2026-07-01',
        dueDate: '2026-07-15',
        lineItems: [
          {
            id: 'li-2',
            description: 'June retainer — 40 hrs @ $135',
            quantity: 40,
            unitPrice: 135,
          },
        ],
        createdAt: '2026-07-01T09:00:00.000Z',
      },
      {
        id: 'i-1003',
        number: 'INV-0003',
        clientId: 'c-acme',
        projectId: 'p-dashboard',
        status: 'sent',
        issueDate: '2026-08-01',
        dueDate: '2026-08-15',
        lineItems: [
          {
            id: 'li-3',
            description: 'Dashboard v2 — 32 hrs @ $120',
            quantity: 32,
            unitPrice: 120,
          },
        ],
        createdAt: '2026-08-01T09:00:00.000Z',
      },
      {
        id: 'i-1004',
        number: 'INV-0004',
        clientId: 'c-northwind',
        projectId: 'p-website',
        status: 'sent',
        issueDate: '2026-07-10',
        dueDate: '2026-07-24',
        lineItems: [
          {
            id: 'li-4',
            description: 'Website redesign — milestone 1',
            quantity: 1,
            unitPrice: 5000,
          },
        ],
        notes: 'Net 14. Milestone 1 of 3.',
        createdAt: '2026-07-10T09:00:00.000Z',
      },
    ],
    timeEntries: [
      {
        id: 't-1',
        projectId: 'p-dashboard',
        date: '2026-08-03',
        hours: 6,
        description: 'Chart component + data hooks',
        billed: false,
        createdAt: '2026-08-03T18:00:00.000Z',
      },
      {
        id: 't-2',
        projectId: 'p-dashboard',
        date: '2026-08-05',
        hours: 4.5,
        description: 'Saved views + filters',
        billed: false,
        createdAt: '2026-08-05T18:00:00.000Z',
      },
      {
        id: 't-3',
        projectId: 'p-website',
        date: '2026-08-06',
        hours: 5,
        description: 'CMS integration',
        billed: false,
        createdAt: '2026-08-06T18:00:00.000Z',
      },
      {
        id: 't-4',
        projectId: 'p-retainer',
        date: '2026-08-07',
        hours: 2,
        description: 'Pipeline hotfix + monitoring',
        billed: false,
        createdAt: '2026-08-07T18:00:00.000Z',
      },
      {
        id: 't-5',
        projectId: 'p-dashboard',
        date: '2026-07-28',
        hours: 7,
        description: 'Real-time socket wiring',
        billed: true,
        createdAt: '2026-07-28T18:00:00.000Z',
      },
    ],
  };
}
